CREATE TABLE IF NOT EXISTS films (
  id VARCHAR(50) PRIMARY KEY,
  rating NUMERIC NOT NULL,
  director VARCHAR(255) NOT NULL,
  tags VARCHAR[] NOT NULL,
  title VARCHAR(255) NOT NULL,
  about TEXT NOT NULL,
  description TEXT NOT NULL,
  image VARCHAR(255) NOT NULL,
  cover VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS schedules (
  id VARCHAR(50) PRIMARY KEY,
  daytime VARCHAR(50) NOT NULL,
  hall VARCHAR(50) NOT NULL,
  rows INTEGER NOT NULL,
  seats INTEGER NOT NULL,
  price NUMERIC NOT NULL,
  taken VARCHAR[] DEFAULT '{}',
  film_id VARCHAR(50) NOT NULL REFERENCES films(id) ON DELETE CASCADE
);
